                    add-to-cart
                    absolute
                    top-2
                    right-2
                    sm:top-4
                    sm:right-4
                    w-7
                    h-7
                    sm:w-10
                    sm:h-10
                    flex
                    items-center
                    justify-center
                    bg-white
                    sm:bg-green-500
                    text-green-500
                    sm:text-white
                    hover:bg-green-500
                    hover:text-white
                    active:bg-green-500
                    active:text-white
                    rounded-full
                    text-base
                    sm:text-xl
                    font-bold
                    leading-none
                    shadow-md
                    transition
                    disabled:bg-gray-200
                    disabled:text-gray-400
                    disabled:cursor-not-allowed
